// Error codes used in the application
export const ERROR_CODES = {
  ALREADY_RESERVED: 'ALREADY_RESERVED',
  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR'
}